### ISSUE TITLE
Thanks for the project

### ISSUE THREAD

**Issue by grantkemp** [Yalantis/CloudKit-Demo.Swift#3]
Just wanted to say thanks- this helped me to start learning Cloudkit really quickly. 
 I used the project to build a companion Mac App also leveraging Cloudkit which lets you subscribe to Cloudkit updates and synchronise your city database. 

I have open sourced it here:
https://github.com/grantkemp/CloudKit-Demo-OSX

**Comment by maksimusenko** [comment]
Hey @grantkemp,
You are welcome!
We are glad that's useful

**Comment by grantkemp** [comment]
I included the copyright message for your plugin so hopefully others will use it. 

Cheers!
